---
# tasks file for roles/os_configuration
- name: Ensure standard corporate DNS servers are configured
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver'
    line: "nameserver {{ primary_dns_server }}"
    state: present
