name: Run systems time clock sync Playbook

on:
  workflow_dispatch:

jobs:
    time_sync:

    runs-on: self-hosted

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show PATH
        run: |
          echo "$PATH"

      - name: Verify important tools
        run: |
          which git
          which ansible
          which ansible-playbook
          which kubectl

      - name: Show inventory
        run: |
          cat hosts

      - name: Run time clock sync playbook
        run: |
        
          ansible-playbook \
            -i hosts \
            playbooks/time_sync.yml \
            -v